services:
  - type: web
    name: btc-predictor-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.src.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000

  - type: web
    name: btc-predictor-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: PORT
        value: 10001 